### ISSUE TITLE
Add to cart wrong quantity in home page

### ISSUE THREAD

**Issue by huyhuana** [grandnode/grandnode#1042]
**Describe the bug**
When one product is marked "Show on homepage" and "Marked as new" and display in home page, the DOM has duplicate element with id = "addtocart_" + @Model.Id + "_EnteredQuantity" (check line 80 in _ProductBox.cshtml). So the quantity always take the first one.

**To Reproduce**
1. Go to Edit product details
2. Set product to "Show on homepage" and "Mark as new". Ensure "catalogsettings.newproductsenabled" is true and Ensure  quantity is showed.
3. Go to homepage
4. In "Featured product" section, increase quantity to 6 of product "A".
5. Go to "New product" section, increase quantity to 3 and click on "Add to cart" button of product "A".
6. See error : the quantity added is 6 instead of 3.

**Expected behavior**
Submit correctly quantity.

**Screenshots**
![image](https://user-images.githubusercontent.com/40843758/101341089-28d0b500-38b3-11eb-9b29-6cdeba475796.png)
![Selection_046](https://user-images.githubusercontent.com/40843758/101341507-c5935280-38b3-11eb-83de-f3fa6a1e7da1.png)
![Selection_047](https://user-images.githubusercontent.com/40843758/101341514-c7f5ac80-38b3-11eb-98c1-68961a8689e8.png)

**Comment by PatrykPorabik** [comment]
Hi, @huyhuana ! 

We know about that issue. To be honest, at the moment, we don't plan to make any fix. To avoid this situation, we recommend not to set the same products on the home page and other sections like new products, recommended products, personalized products, etc. Because the same will happen with the rest of the customized products section.
