### ISSUE TITLE
4.0.0 - WebHelper.RestartAppDomain stops app instead of restart

### ISSUE THREAD

**Issue by brunobertechini** [grandnode/grandnode#146]
When running the solution using v4.0.0 couple actions call WebHelper.RestartAppDomain

- Menu - Restart Application
- Installing Plugin
- Uninstalling Plugin

I would like to know if this feature is considered finished or still under development.

As I can see the code calls:

Microsoft.AspNetCore.Hosting.IApplicationLifetime.StopApplication() and thats it.

When debugging this causes debugger to stop.
When deployed this causes app to shutdown.

Are there any plans to change or disable this behavior ?

Bruno

**Comment by KrzysztofPajak** [comment]
If you use Visual Studio and you will try restart application by button Restart, application never start, you need start again (from VS). 
It's standard behavior.
If you run application on IIS server after restart, application run again automaticly.
We can't touch file web.config because this solution doesn't work on MAC or LINUX only.

Regards
Krzysztof

**Comment by KrzysztofPajak** [comment]
If you use Visual Studio and you will try restart application by button Restart, application never start, you need start again (from VS). 
It's standard behavior.
If you run application on IIS server after restart, application run again automaticly.
We can't touch file web.config because this solution doesn't work on MAC or LINUX only.

Regards
Krzysztof

**Comment by brunobertechini** [comment]
Understood. So thats a expected behavior while debugging. This is kinda counter-productive for plugin development but it is the way it is.

Thanks for your answer.

**Comment by KrzysztofPajak** [comment]
We made some exception for windows server, when you click restart application we touch file web.config. For now this is temporary solution.

**Comment by brunobertechini** [comment]
I see thanks.

What about docker containers ? When the app is restarted is the container stopped ?

For example if we run dotnet Grand.Web.dll

**Comment by BilalHasanKhan** [comment]
I would like this to be reopened what the op really wanted was something like this 
https://stackoverflow.com/questions/36121999/how-to-restart-asp-net-core-app-programmatically
