### ISSUE TITLE
Order Queue

### ISSUE THREAD

**Issue by yarsrvenge** [grandnode/grandnode#217]
When you have a lot of people placing orders on a multi-instance implementation, it appears there are write conflicts occurring as seen by the error below during a load test.

I am wondering if one way to address this is an order processing queue so that there is no potential for a duplicate order being created.  

Error while placing order. Error 1: A write operation resulted in an error. E11000 duplicate key error collection: grandnode.Order index: OrderNumber dup key: { : 2182 } 

A write operation resulted in an error. E11000 duplicate key error collection: grandnode.Order index: OrderNumber dup key: { : 2182 }

**Comment by KrzysztofPajak** [comment]
Hi @yarsrvenge,
Because Mongodb not supported autoincrement type yet, so this solution can work with one server. There are many ways to solve this problem.
I may suggest this solutions:
1. Add new table "Transaction" with something like this: https://docs.mongodb.com/manual/tutorial/perform-two-phase-commits/
or
2. OrderNumber field in the "order" Collection - instead of checking the max - insert 
 for examle - Ticks from Datetime. Ticks, always will be unique and higher (but it will not be increase by one point).
In stores where there are a large number of orders (eg ebay, amazon) - the field with the order number reminds GUID (abbreviated). Order number from amazon: 303-7393838-5671130, ebay order number: 110418846393-22712185031
But if you have any other idea, please share it.

Regards
Krzysztof

**Comment by yarsrvenge** [comment]
I made some code changes to use a combination of ticks and GUID which is close to your option 2 and mitigated that issue.
