### ISSUE TITLE
The schedule task "Send emails" don't work 

### ISSUE THREAD

**Issue by JosigBarcos** [grandnode/grandnode#577]
The schedule task "Send emails" don't work in GrandNode 4.40

When the application start, this Fatal Error is produced:

System.InvalidOperationException: Wrong enum value - value must be of 0,10,20 etc at Grand.Services.Tasks.RegistryGrandNode..ctor(List`1 tasks, Boolean throwException) in /app/Grand.Services/Tasks/RegistryGrandNode.cs:line 18 at Grand.Framework.Infrastructure.TaskHandlerStartup.Configure(IApplicationBuilder application) in /app/Grand.Framework/Infrastructure/TaskHandlerStartup.cs:line 42

I want to configure the sending of emails every minute

**Comment by PatrykPorabik** [comment]
It's known issue, but it will be fixed in 4.50 version. because we are going to remake the schedule tasks mechanism. For now, please edit all of the enabled schedule tasks, reveal all additional fields in interval and change their value from 0 to 1 for example. Then go back to every minute interval and save changes. Everything will work fine after that.

**Comment by JosigBarcos** [comment]
Great, it worked!
