### ISSUE TITLE
Improve the B2B Features

### ISSUE THREAD

**Issue by PatrykPorabik** [grandnode/grandnode#601]
Improve the B2B Features

**Comment by wwrighter** [comment]
The ability to setup and control Net Terms on a customer account would be a great feature for B2B. 

For example: some customers may belong to a "group" or have an assigned "role" for Net 30. Allowing 30 days until payment is necessary. This might be handled off the ecommerce platform by cheque, electronic funds transfer, etc. 

Others may have Net 15 or Net 45.

**Comment by wwrighter** [comment]
Another worthy feature to at least consider would be creating a way that customers (primarily B2B) customers could specify fields that perhaps could be eatablished by the merchant (store owner) using custom fields. 

I.e. 

PO Number:  <alpha numeric>
TAG: <alpha numeric>
Notes: <alpha numeric>

At a single page checkout would most likely be the most ideal. An additional checkbox would or consideration for shipping would also be : 

Optional Shipping:

Pick Up In Store [  ]
Ship via Customer Account (dropdown with customers preferred shipping method or option to add new)

**Comment by scharada** [comment]
B2B order need to generate PO with PO number tracking. Invoices need to be issued for POs and payment tracked (partial and full) for a given invoice,  
Permissions need to be set to who can issue PO, who can issue invoice, who can alter invoice, who can pay invoice ... these are the basics.
PO and Invoice templates need to be set for each Party using the b2b feature (vendor customer, store owner) ...
and since we are here , why not make vendors grouped by type : such as WholeSeller, Distributor, Retailer ...
this can allow a user to create a product and pricings only for a specific type of vendors ...
