### ISSUE TITLE
Out of stock products to end of search and categories pages

### ISSUE THREAD

**Issue by gelinski** [grandnode/grandnode#669]
Keeping the current sorting logic, add a default sort by product availability, throwing the unavailable products (out of stock) to the bottom of the lists. It is important to decrease page rejections by users.

**Comment by Leonardo-Ferreira** [comment]
This is a double-edge kinda of deal... if we move products which have 0 stock, we might hurt sales because people might believe that the store doesn't SELL the product (since it might end-up in page 10 of the search)... this should either be a store-wide-configuration or something that the end-user can choose

**Comment by wwrighter** [comment]
My - assumption - is that many store owners will not be keeping vigilant upkeep of inventory levels. Unless of course they have integrated connections between their inventory management systems and grandnode.

**Comment by Leonardo-Ferreira** [comment]
@wwrighter you're correct. I've seen this in a lot of real world establishments. In fact, small stores even prefer to "turn off" inventory management...

**Comment by gelinski** [comment]
But if not doing it, all customers will see the same products in same default order. If the product is at the top of list, but with no stock, the customer will give up searching, because he is viewing always that out-of-stock product in firsts places on grid. Therefore, the customer will reject the site and the store owner will loose sales. We identified this problem on NopCommerce and fixed it, but as GrandNode works with MongoDB, we cannot create stored procedures (obviously) as well.

Some note of "turning off" inventory management: The store owner has physical stock of products, if he doesn't control inventory, he will sell more products that he really have, and will create a huge problem. So, turning off inventory management **is not an option**! @wwrighter it can be the scenario on your region/country, but there things don't work like that. The store owners control and integrate stock between its ERP software and GN.

**Comment by wwrighter** [comment]
Another assumption but I would think that the majority of clients for GN will be small to medium sized businesses. Having worked for a few smaller businesses throughout my life - i can only imagine that most will not spend the money on custom integrations between ERP/Inventory Manage and GN atleast not until they scale. For the larger companies or those willing to spend on custom integrations, it is definitely a subset that should not be forgotten. I believe in scaling. I feel forcing GN customers to incorporate inventory management both online and in their own software (quickbooks, salesforce, etc etc etc) simultanrous or making integration between the two mandatory, would be creating more of a headache for a lot of operations who are looking to simply expose products to a larger audience. 

I personally feel the few things that promotes early and prolonged adoption as well as larger "box" store audiences is very tight security, payment processing and the flexibility of theme customization with a well developed and well documented API. Centralized hosting seems to be a big push too. I guess that's a pretty broad stroke, so maybe I'm just stating the obvious.

**Comment by gelinski** [comment]
Forget the point about integration, it was just an example. What I'm trying to say is that the products always will appear in the same sort, even out-of-stock products appears in the beginning of grid. Not all store owners will use the integration, it's ok and about this I study each case. But some owners will work exclusively with GN and have to track inventory. If turning off this, he assumes the risk of selling a product that he doesn't have and taking legal issues and/or be sued because of this problem, either for not having stock or that product is very difficult to take from supplier. Another problem is that not all users are willing to navigate to another pages, open page by page until find some product that are available to be sold. The user will give up searching and will get out of store. Don't think programmatically, it's a real scenario. One of instances published by us is taking penalties for high rejection of store.

**Comment by Leonardo-Ferreira** [comment]
@gelinski are you sure that the rejection is happening because out-of-stock products are being displayed? Rejection is something really difficult to pinpoint. I would recommend a tangible experiment: fork the release, implement the desired behaviour, monitor and report the result.

I've worked on a few small e-commerces and on a really big one (GAP), and I can tell you that, unless all the products on several first-page-results are out of stock, he's not leaving because of that. If he is searching for a specific product and it is out, he will definitely leave, regardless of the others on the page. If you push this to the bottom of the list, or page 10, you might get a sale while he flip pages, but that's a minor chance...

@wwrighter I must say that I believe that centralised hosting, in a Multi-Tenant fashion, would be a major offering... several small-medium business choose other platforms such as WIX, because they have zero technical staff. The staff for these business are usually composed of the Owner, a accountant/finance guy, and sales team... maybe this should be handled on another topic

**Comment by gelinski** [comment]
@Leonardo-Ferreira tell it to store owner, that was receiving several complaints about this problem. After we solved it at NopCommerce, the store has the rejection rate decrease significantly.
P.s.: the store is small business. If myself is searching something between categories and/or searches in any store, the last thing that I want to see is an out-of-stock product. If there are much more products with this condition, I'll get out of store and look at the store competitor. And several people shall think at the same way.

**Comment by Leonardo-Ferreira** [comment]
My fiancé is a store owner! your report is completely unexpected and does match any scenario I've ever lived. I am assuming that from a page of 20 products, you had an average of 2 (10%) that were out of stock, and when you pushed those to the bottom, your retaining statistic improved by 50% or more. Are my assumptions correct? if the store you're talking about had a 90% out of stock page, I'd say that the problem is more on the line of "supply-chain" and/or "inventory management" and/or store management than "search"...

If my assumption is correct: Understand that there are 2 types of visitors: the shoppers, and the browsers. Assuming that everyone that visits the store is a shopper or even a potential buyer at that moment is a big mistake. Some people will come to the store with the intent to evaluate prices ONLY. For those, the fact the product is out of stock is almost irrelevant. Acknowledging that the product is sold there, and gathering its price is ALL they intend.

IF we're dealing with buyers, we have to then understand the intent of the search: if I search for "MacBook Pro 2019 retina 32gb Space Gray" it really doesn't matter if its the first or the last: if it is out of stock, im out, WITH the possible upsetting detail that I have to scroll/navigate/paginate only to discover that you're out of stock. Shoppers don't golf-search terms like "T-Shirts" or "macbook". Shoppers are more direct. If they want a t-shirt for example, they usually query for a specific size, brand, ad style (v neck, etc..) or price...

A approach I've seen working is pushing out-of-stock products a few spots down the list, like 5-7 spots... This way the search engine is still smart/reliable from the users point of view while promoting others available products...

**Comment by gelinski** [comment]
> if I search for "MacBook Pro 2019 retina 32gb Space Gray" it really doesn't matter if its the first or the last: if it is out of stock, im out
You are considering the very specific search. If I click in some category (specific or not), what's the sense of showing the out-of-stock products in firsts lines/pages? I'm looking for a notebook Lenovo, for example. There is no stock of it, but can have some stock of HP, Samsung, etc., and it is in lasts pages. Until I figure out it, I already gave up buying in this store. Don't take in consideration only searches, the platform should offer similar products that has stock for selling. If the store has only 20 items ok, but if I'm listing all products from specific category (all from Electronics) having 100, 200+ items, will I have to open each product to see if it has stock? It's no sense!

**Comment by PatrykPorabik** [comment]
It has been implemented in 4.90.0 - #1078
