### ISSUE TITLE
When saving a product, its m:n fields aren't updated in admin until cache manually cleared

### ISSUE THREAD

**Issue by ghost** [grandnode/grandnode#676]
1. Create a product
2. Save it
3. ???
4. Modify any n:m (add/remove) :
    - Tags
    - Categories
    - Manufacturer
    - Attribute Values
    - etc..
5. Save
6. Changes made to n:m seems to not work
7. Clear the cache
8. Changes made to n:m now appear in admin

I can understand that's correct behaviour for frontend, but for admin, the cache should not apply there.

**Comment by dctremblay** [comment]
This can be awkward because if someone is not aware of this bug his reflex will probably be to retry it "ohh that's true I remember I have to clear the caches" :

1. Add product attribute
2. Save
3. Changes not reflected
4. Re-add product attribute at point 1
5. Clear cache
6. The product is duplicated 2x which is very confusing for people not aware of this bug

**Comment by PatrykPorabik** [comment]
Have you configured the progressive web app / service worker?

**Comment by dctremblay** [comment]
I do not know what it is.

It is the stock image from DigitalOcean

**Comment by petarvu** [comment]
We are experiencing the same issue, after we tested with the stock image from DigitalOcean. What is the solution for this? @dctremblay @PatrykPorabik

**Comment by PatrykPorabik** [comment]
@petarvu Do you have progressive web apps configured in your store?

**Comment by petarvu** [comment]
@PatrykPorabik No PWA configured, running the stock image from DO.

**Comment by PatrykPorabik** [comment]
Can you try to simulate this issue on demo? 
https://demo.grandnode.com/
login: admin@yourstore.com
password: 123456
