### ISSUE TITLE
Migration tool nopCommerce > grandnode

### ISSUE THREAD

**Issue by gelinski** [grandnode/grandnode#788]
Do someone here know if there is some tool that can migrate the nopCommerce application to grandnode? I found [this link](https://grandnode.com/mssql-to-mongodb-migration-tool), but I can't "buy" because it returns for me "Product not published".

The both platforms versions are the latest (grandnode 4.60 and nopCommerce 4.20).

Best regards.

**Comment by PatrykPorabik** [comment]
Hello.
It's not possible to get this plugin because the architecture of GrandNode and nopCommerce has changed a lot since the time when we've made that plugin. 

However there are still few possibilities to achieve that:
- API
- Manual imports

If you want, reach us at support@grandnode.com, we can talk about the most efficient way for you.

**Comment by gelinski** [comment]
Ok, I'll evalute here and will contact you soon, because we have just one customer using nopCommerce and the others using GrandNode, and we really want to join this unique nop customer to GN team.

Tks for comprehension :-)
